dataset:
  name: BigEarthNet
  bands: [0,1,2,3,4,5,6,7,8,9,10,11] #[] #
  subset_size: 50000 #50000
  subset_size_test: 500

dataloader:
  batch_size: 32
  num_workers: 10
  pin_memory: True
  shuffle: False

compressai_model:
 pretrained: Trude
 quality: 8
 N: 192 
 M: 64
 V: 43

training:
  lmbda: 0.5 #Bit-rate distortion parameter 
  lr: 0.0005
  optim: "Adam"
  lr_aux: .0005
  optim_aux: "Adam"
  epochs: 5
  clip_max_norm: 1.0
  
randomseed: 2345

  

