dataset:
  name: BigEarthNet
  bands: [1,2,3] #[] #
  subset_size: 50000 #50000
  subset_size_test: 500

dataloader:
  batch_size: 4
  num_workers: 10
  pin_memory: True
  shuffle: False

compressai_model:
 pretrained: Trude
 quality: 8
 N: 192 
 M: 192
 V: 43

preprocessing:
  coordinate_encoding: 'positional' # embedding
  coordinate_num_bins: 100
  coordinate_embedding_dim: 64

training:
  lmbda: 0.5 #Bit-rate distortion parameter 
  lr: 0.0005
  optim: "Adam"
  lr_aux: .0005
  optim_aux: "Adam"
  epochs: 5
  clip_max_norm: 1.0
  
randomseed: 2345

  

