dataset:
  name: BigEarthNet
  bands: [1,2,3] 
  subset_size: 100000
  subset_size_test: 500
  subset_size_val: 500

dataloader:
  batch_size: 32
  num_workers: 10
  pin_memory: True
  shuffle: False

compressai_model:
 pretrained: True
 quality: 8
 N: 192 
 M: 320
 V: 64

preprocessing:
  coordinate_encoding: 'positional_random' # embedding
  coordinate_num_bins: 100
  coordinate_embedding_dim: 64

training:
  lmbda: 0.05 #Bit-rate distortion parameter 
  lr: 0.0001
  optim: "Adam"
  lr_aux: 0.0001
  optim_aux: "Adam"
  epochs: 50
  clip_max_norm: 1.0
  
randomseed: 2345


